import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../components/Header/Header';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="bg-define min-h-screen px-8 md:px-10 lg:px-20 xl:px-32">
                    <Header />
                    <div className="mb-20 py-10">{children}</div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
